
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { Question } from '../types';

// ── COLOR PALETTE ──
const COLORS = {
  primary: '#4338ca',
  primaryLight: '#eef2ff',
  emerald: '#059669',
  emeraldLight: '#ecfdf5',
  slate900: '#0f172a',
  slate800: '#1e293b',
  slate700: '#334155',
  slate600: '#475569',
  slate500: '#64748b',
  slate400: '#94a3b8',
  slate200: '#e2e8f0',
  slate100: '#f1f5f9',
  slate50: '#f8fafc',
  white: '#ffffff',
};

const s = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: COLORS.slate800,
    backgroundColor: COLORS.white,
    paddingTop: 40,
    paddingBottom: 50,
    paddingHorizontal: 40,
  },
  headerBar: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.slate200,
    paddingBottom: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: COLORS.slate900,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 9,
    color: COLORS.slate500,
    marginTop: 4,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.primaryLight,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 16,
    fontWeight: 700,
    color: COLORS.primary,
  },
  statLabel: {
    fontSize: 7,
    color: COLORS.slate500,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  questionCard: {
    backgroundColor: COLORS.slate50,
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.slate200,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
  },
  questionNumber: {
    fontSize: 8,
    fontWeight: 700,
    color: COLORS.primary,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  questionText: {
    fontSize: 10,
    color: COLORS.slate800,
    fontWeight: 700,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  optionRow: {
    flexDirection: 'row',
    marginBottom: 3,
    paddingLeft: 8,
  },
  optionLetter: {
    fontSize: 9,
    fontWeight: 700,
    width: 18,
    color: COLORS.slate600,
  },
  optionText: {
    fontSize: 9,
    color: COLORS.slate700,
    flex: 1,
    lineHeight: 1.4,
  },
  optionCorrect: {
    color: COLORS.emerald,
    fontWeight: 700,
  },
  answerSection: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.slate200,
  },
  answerLabel: {
    fontSize: 8,
    fontWeight: 700,
    color: COLORS.emerald,
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  explanationText: {
    fontSize: 9,
    color: COLORS.slate600,
    lineHeight: 1.4,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: COLORS.primary,
    marginTop: 4,
  },
  keyPointBadge: {
    fontSize: 7,
    fontWeight: 700,
    color: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 7,
    color: COLORS.slate400,
  },
  pageBreak: {
    marginTop: 16,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
    paddingBottom: 8,
    marginBottom: 16,
  },
  answerKeyTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: COLORS.slate900,
    marginBottom: 4,
  },
});

const PageFooter = () => (
  <View style={s.footer} fixed>
    <Text>Bank Soal — Generated by Noodl ( @_@)⌐■-■</Text>
    <Text render={({ pageNumber, totalPages }) => `Halaman ${pageNumber} / ${totalPages}`} />
  </View>
);

interface BankSoalPdfProps {
  questions: Question[];
  title: string;
  includeAnswers: boolean;
}

export const BankSoalPdf: React.FC<BankSoalPdfProps> = ({ questions, title, includeAnswers }) => {
  const now = new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });

  // Group by keyPoint
  const grouped: Record<string, Question[]> = {};
  questions.forEach(q => {
    const key = q.keyPoint || 'Umum';
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(q);
  });
  const groupKeys = Object.keys(grouped).sort();

  return (
    <Document title={`Bank Soal - ${title}`} author="Noodl App" subject={title}>
      <Page size="A4" style={s.page} wrap>
        <PageFooter />

        {/* HEADER */}
        <View style={s.headerBar} fixed>
          <Text style={s.title}>BANK SOAL</Text>
          <Text style={s.subtitle}>Topik: {title} • {now} • {questions.length} Soal</Text>
        </View>

        {/* STATS */}
        <View style={s.statsRow}>
          <View style={s.statItem}>
            <Text style={s.statValue}>{questions.length}</Text>
            <Text style={s.statLabel}>Total Soal</Text>
          </View>
          <View style={s.statItem}>
            <Text style={s.statValue}>{groupKeys.length}</Text>
            <Text style={s.statLabel}>Topik</Text>
          </View>
          <View style={s.statItem}>
            <Text style={s.statValue}>
              {questions.filter(q => !q.type || q.type === 'MULTIPLE_CHOICE').length}
            </Text>
            <Text style={s.statLabel}>Pilihan Ganda</Text>
          </View>
          <View style={s.statItem}>
            <Text style={s.statValue}>
              {questions.filter(q => q.type === 'TRUE_FALSE').length}
            </Text>
            <Text style={s.statLabel}>Benar/Salah</Text>
          </View>
        </View>

        {/* QUESTIONS (without answers) */}
        {groupKeys.map((topic, gIdx) => (
          <View key={gIdx}>
            {/* Topic Header */}
            <View style={{ marginBottom: 8, marginTop: gIdx > 0 ? 12 : 0 }}>
              <Text style={{ fontSize: 12, fontWeight: 700, color: COLORS.primary }}>
                {topic}
              </Text>
              <View style={{ height: 1, backgroundColor: COLORS.slate200, marginTop: 4 }} />
            </View>

            {grouped[topic].map((q, qIdx) => {
              const globalIdx = questions.indexOf(q);
              return (
                <View key={qIdx} style={s.questionCard} wrap={false}>
                  <Text style={s.questionNumber}>SOAL #{globalIdx + 1}</Text>
                  
                  {q.keyPoint && (
                    <Text style={s.keyPointBadge}>{q.keyPoint}</Text>
                  )}

                  <Text style={s.questionText}>{q.text}</Text>

                  {/* True/False indicator */}
                  {q.type === 'TRUE_FALSE' && q.proposedAnswer && (
                    <Text style={{ fontSize: 9, color: COLORS.slate600, marginBottom: 4, fontStyle: 'italic' }}>
                      Pernyataan: "{q.proposedAnswer}"
                    </Text>
                  )}

                  {/* Options */}
                  {q.options && q.options.length > 0 && q.options.map((opt, oIdx) => (
                    <View key={oIdx} style={s.optionRow}>
                      <Text style={s.optionLetter}>{String.fromCharCode(65 + oIdx)}.</Text>
                      <Text style={[
                        s.optionText,
                        includeAnswers && oIdx === q.correctIndex ? s.optionCorrect : {}
                      ]}>
                        {opt} {includeAnswers && oIdx === q.correctIndex ? '✓' : ''}
                      </Text>
                    </View>
                  ))}

                  {/* Fill in blank answer */}
                  {q.type === 'FILL_BLANK' && (
                    <Text style={{ fontSize: 9, color: COLORS.slate500, fontStyle: 'italic' }}>
                      (Isian Singkat)
                    </Text>
                  )}

                  {/* Inline answer + explanation */}
                  {includeAnswers && (
                    <View style={s.answerSection}>
                      <Text style={s.answerLabel}>
                        JAWABAN: {q.type === 'FILL_BLANK' 
                          ? (q.correctAnswer || '') 
                          : `${String.fromCharCode(65 + q.correctIndex)}. ${q.options[q.correctIndex] || ''}`}
                      </Text>
                      {q.explanation && (
                        <Text style={s.explanationText}>{q.explanation}</Text>
                      )}
                    </View>
                  )}
                </View>
              );
            })}
          </View>
        ))}

        {/* ANSWER KEY (only if answers NOT included inline) */}
        {!includeAnswers && (
          <View break>
            <View style={s.pageBreak}>
              <Text style={s.answerKeyTitle}>KUNCI JAWABAN</Text>
              <Text style={s.subtitle}>{title}</Text>
            </View>
            {questions.map((q, i) => (
              <View key={i} style={{ marginBottom: 6, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: COLORS.slate100 }}>
                <Text style={{ fontSize: 9, fontWeight: 700, color: COLORS.slate800 }}>
                  #{i + 1}: {q.type === 'FILL_BLANK' 
                    ? (q.correctAnswer || '') 
                    : `${String.fromCharCode(65 + q.correctIndex)}. ${q.options[q.correctIndex] || ''}`}
                </Text>
                {q.explanation && (
                  <Text style={{ fontSize: 8, color: COLORS.slate500, marginTop: 2, lineHeight: 1.3 }}>
                    {q.explanation}
                  </Text>
                )}
              </View>
            ))}
          </View>
        )}
      </Page>
    </Document>
  );
};
